var posts = [ 
  {
    slug: 'nodejs-chat-app',
    title: 'Build a Chat App in Node.js with Socket.io',
    cat: 'coding'
  },
  { slug: 'node-child-processes',
    title: 'Node.js External and Child Processes',
    cat: 'coding' },
  { slug: 'validating-https-nodejs',
    title: 'Validating HTTPS Connections in Node.js',
    cat: 'coding' },
  { slug: 'node-udp',
    title: 'Sending UDP Datagrams with Node.js',
    cat: 'coding' },
  { slug: 'nuts-bolts-problem',
    title: 'The Nuts and Bolts Problem (An Approach)',
    cat: 'coding' },
  { slug: 'node-fs',
    title: 'Using the Node.js FS Module',
    cat: 'coding' },
  { slug: 'frontend-crawler',
    title: 'How to Build a Frontend Web Crawler',
    cat: 'coding' },
  { slug: 'php-vs-node', title: 'PHP vs Node.js', cat: 'coding' },
  { slug: 'logout-button-css',
    title: 'Logout Buttons with CSS',
    cat: 'coding' },
  { slug: 'software-cliche',
    title: 'Design Pattern or Cliché?',
    cat: 'product' },
  { slug: 'modern-css-buttons',
    title: 'Modern CSS Buttons',
    cat: 'coding' },
  { slug: 'php-good',
    title: 'PHP is a Good Language',
    cat: 'coding' },
  { slug: 'css-buttons',
    title: '12 Professional CSS Buttons',
    cat: 'coding' },
  { slug: 'wordpress-plugins',
    title: '6 Tips for Building Premium Wordpress Plugins',
    cat: 'coding' },
  { slug: 'how-to-hide-that-you-use-wordpress',
    title: 'How to Hide that You Use Wordpress',
    cat: 'coding' },
  { slug: 'jan-smuts-legacy',
    title: 'The Legacy of Jan Smuts in South Africa',
    cat: 'travel' },
  { slug: 'entertainment-luxury',
    title: 'Entertainment is Not a Luxury',
    cat: 'travel' },
  { slug: 'market-identity',
    title: 'How to Use Market Segmentation and Discover Your Business\' Core Identity',
    cat: 'product' },
  { slug: 'trends-fads',
    title: 'Trends, Fads, and Recognizing the Difference',
    cat: 'product' },
  { slug: 'google-web-designer-review',
    title: 'Google Web Designer First Impressions: Review',
    cat: 'product' },
  { slug: 'gender-graduation',
    title: 'Women are Outperforming Men - Confirmation from Commencement Day',
    cat: 'psychology' },
  { slug: 'habits', title: 'Habit Formation', cat: 'psychology' },
  { slug: 'gendered-graffiti',
    title: 'Collaborative and Depreciative: Gendered Graffiti in a College Bathroom',
    cat: 'psychology' },
  { slug: 'neuromarketing',
    title: 'What is Neuromarketing?',
    cat: 'psychology' },
  { slug: 'gurus', title: 'The Modern Guru', cat: 'psychology' } ];

exports.posts = posts;